### PR TITLE
Rollup build for use without webpack

### PR DESCRIPTION
**Pull request by tonypolik**
Hi,

I'm working on a project in which we are using RequireJS, Vue, Handsontable and vanilla Javascript.  
With our current setup, we cannot use this wrapper: we need an AMD compatible build.  

This PR adds a `npm run build` command that compiles the component into various formats (amd, umd, iife, cjs).  

The build file is based on [this one](https://github.com/vuejs/vue-test-utils/blob/000549e9246a727aa97ce0f58dace3392f787c10/build/build.js) from the [vue-test-utils project](https://github.com/vuejs/vue-test-utils).

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for your time to report it @tonypolik . 
Can you move the changes to develop branch, please?

**Comment by tonypolik** [comment]
Done. Thank you!

**Comment by AMBudnik** [comment]
Can I also ask you to [sign CLA](https://docs.google.com/forms/d/1sNbsA7MGelGNxsBRvBoY3swq7YEMYhXNpR7NPk4tWPo). Without it, we won't be able to publish the changes.

**Comment by jansiegel** [comment]
@tonypolik, we refactored the whole wrapper structure, so now it creates a umd build, and can be imported from `@handsontable/vue` (or `@handsontable-pro/vue`). Can you confirm it solves your problem?

**Comment by tonypolik** [comment]
@jansiegel It does. Awesome, nice job!
Thank you!

**Pull request closed without merging**
