### PR TITLE
Correct passing props to the renderer and editor components.

### PR DESCRIPTION
**Pull request by jansiegel**
### Context
Fix a problem with being unable to read the props passed to the renderer/editor components from inside of the components.

### How has this been tested?
Added a test case.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #172

### CODE REVIEW

**Comment by jansiegel** [comment]
A quick example of the fixed issue:

Before: https://codesandbox.io/s/wonderful-almeida-bs72e
After: https://codesandbox.io/s/little-microservice-50cfo

**Review by wojciechczerniak — APPROVED** [review]
Awesome idea 👍

**Comment by magikadev** [comment]
It's working. Thanks @jansiegel

**Comment by magikadev** [comment]
How can I use it on my website before release fixed version?

**Comment by jasonlfunk** [comment]
@magic990619 You can clone the repo and build it yourself. :)

But I can't wait for a new release.

**Comment by magikadev** [comment]
@jasonlfunk 
I can see that @jansiegel committed to develop branch.
https://github.com/handsontable/vue-handsontable-official/tree/develop
Would you please tell me how to build it my self and use it on my Vue project?

**Comment by jasonlfunk** [comment]
You can clone the repo locally, then run npm install, then npm build. Then what I did was linked it to “/node_modules/@handsontable/vue” and it worked.

**Comment by magikadev** [comment]
Hi, @pnowak , @jansiegel , @jasonlfunk

Passing props is working well on codesandbox.
https://codesandbox.io/s/clever-bardeen-jvt00
But it's not working on my project. I cloned the develop branch, build it and use it on my project.
Attached is the one that I built and use in the project. (/node_modules/@handsontable)
[@handsontable.zip](https://github.com/handsontable/vue-handsontable-official/files/4787991/%40handsontable.zip)
Would you please have a look what's wrong?

Thank you.

**Comment by pnowak** [comment]
Hi @magic990619 

It's better to keep the same question in one place.

So please follow in this thread - https://github.com/handsontable/vue-handsontable-official/issues/177#issuecomment-643201997

**Comment by AMBudnik** [comment]
Released in v [5.1.0](https://github.com/handsontable/vue-handsontable-official/releases/tag/5.1.0)

**Pull request merged**
