### PR TITLE
Update syntax highlighting in README

### PR DESCRIPTION
**Pull request by dflock**
Github supports highlighting .vue files, so I updated the syntax highlighting in the README to use that.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for the suggestion. Surely it will benefit the readme.

**Comment by AMBudnik** [comment]
Please [sign CLA](https://docs.google.com/forms/d/1sNbsA7MGelGNxsBRvBoY3swq7YEMYhXNpR7NPk4tWPo). Without it, we won't be able to publish the changes.

Also, sorry I did not check it before but could you change the branch to `develop`?

**Comment by dflock** [comment]
I've signed the CLA. You should really hand out the preview/fill form link to that, not the edit link.

**Comment by AMBudnik** [comment]
You're right @dflock 

thanks for spotting that.

**Pull request closed without merging**
