### PR TITLE
Fix types.ts to work with TS 3.7.x

### PR DESCRIPTION
**Pull request by dlkulp**
Update circular reference on types.ts that broke with breaking changes introduced in TS 3.7.x - see [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict).  Also fix 4 vulterabilities (3 high, 1 moderate) with release version update to `rollup-plugin-uglify`.

### Context
Current builds with TypeScript @3.7.x throw the error: 

    ERROR in [at-loader] ./node_modules/@handsontable/vue/types.d.ts:4:10
        TS2440: Import declaration conflicts with local declaration of 'HotTableProps'.

### How has this been tested?
`npm run test` - all passed.  Also, this only removes a circular reference from the types file, ie: it's removing an import that came from an export in the same file.  The definition for the types is still in the file.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #145 Import declaration conflicts with local declaration of 'HotTableProps'.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you for sharing the pull request and signing CLA.

**Comment by dlkulp** [comment]
@AMBudnik Not to be pushy, but any idea on a time frame here?  Would like to integrate these changes into my project soon!

**Comment by AMBudnik** [comment]
I'll mention the missing review to the developers.

**Comment by dlkulp** [comment]
Hey, any updates?  I would like to be able to use your package....

**Comment by AMBudnik** [comment]
I've been that `this could be the right time to update`. They need to ake some more tests and then we'll update the PR.

**Comment by rtroost** [comment]
Could we please move this along?

**Comment by AMBudnik** [comment]
Hey Guys, we are working on the very important version of Handsontable (vanilla) that we are planning to release in parts. We will update the dependencies of wrappers but this cannot be done before the main version.

**Review by jansiegel — APPROVED** [review]

**Comment by AMBudnik** [comment]
Cool, thanks for the prompt response @jansiegel

**Comment by nilehmann** [comment]
Hi, I'm getting into the error. Have the fixed been integrated into any release? Just want to check if I have to update or just wait.

**Comment by AMBudnik** [comment]
Hi @nilehmann we did not release a new version yet (we have a lot of work with v8 - Vanilla). However, I will make sure to ping you once we release a new Handsontable for Vue version.

**Comment by nilehmann** [comment]
Thanks @AMBudnik I appreciate it :)

**Comment by AMBudnik** [comment]
Hey @nilehmann @rtroost the day has come! We've just released Handsontable for Vue 5.0.0 when this fix is merged. We appreciate any feedback :-)

Thank you for the changes @dlkulp 

We needed to push a quick fix in a patch so I'd recommend using 5.0.1.

**Pull request merged**
