### PR TITLE
If a key is set on a custom editor component, include it in the editorCache key

### PR DESCRIPTION
**Pull request by jasonlfunk**
### Context
With the merging of #173, it's now possible to pass props to custom editors. However, in my use case, I wanted to use the same editor component but pass different props for the different columns. However, since the editor cache was caching by the component's name only, it would only use the first column's editor.

### How has this been tested?
I've added a test which mounts the same editor twice with two different keys and ensured that the props are different.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Related issue(s):
1. #173 

### Checklist:

- [X] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by pnowak** [comment]
Hi @jasonlfunk 

Thank you for your effort and work.

Can you sign this Contributor License Agreement -https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1&usp=send_form - to allow us to publish your changes to the code?

This is the first of our contributing rules - https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md

**Comment by jasonlfunk** [comment]
> Hi @jasonlfunk
> 
> Thank you for your effort and work.
> 
> Can you sign this Contributor License Agreement -https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1&usp=send_form - to allow us to publish your changes to the code?
> 
> This is the first of our contributing rules - https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md

Done.

**Comment by pnowak** [comment]
Thank you @jasonlfunk

**Review by jansiegel — APPROVED** [review]
@jasonlfunk This is pretty cool! Plus, it's backward-compatible, if there's no `key` passed to the editors.

I'll merge it to the `develop` branch.

**Comment by aninde** [comment]
We need additional tests for this new feature and information in the docs.

**Comment by AMBudnik** [comment]
Hi @jasonlfunk 

I'm happy to announce that this change has been published under v 5.1.0. Thank you for your collaboration.

**Pull request merged**
